import {statMod,degree} from './math.mjs';
const {HandlebarsApplicationMixin}=foundry.applications.api;
const esc=s=>foundry.utils.escapeHTML(String(s??''));
class CarlActor extends Actor {
 prepareDerivedData(){super.prepareDerivedData();const s=this.system;for(const st of Object.values(s.stats)){st.total=Math.max(1,st.base+st.bonus);st.mod=statMod(st.total);}s.slot=this.type==='crawler'?s.stats.con.mod:s.mob.slot;if(this.type==='crawler')s.health.max=10;s.mana.max=s.stats.int.total;}
 async check(label,stat,rank=0,untrained=false){if(!this.isOwner)return;const s=this.system;let mode=untrained&&s.roll.mode!=='advantage'?'disadvantage':untrained?'normal':s.roll.mode;let die=mode==='advantage'?'2d20kh':mode==='disadvantage'?'2d20kl':'1d20';const roll=await new Roll(`${die}+${s.stats[stat].mod}+${rank}+${s.roll.bonus}`).evaluate();const n=roll.dice[0].results.find(r=>r.active).result;await roll.toMessage({speaker:ChatMessage.getSpeaker({actor:this}),flavor:`<div class="carl-card"><small>WORLD DUNGEON // CHECK</small><h3>${esc(label)}</h3><b>${degree(n,roll.total,s.roll.difficulty)}</b><p>Difficulty ${s.roll.difficulty} • ${esc(mode)} • Rank ${rank}</p></div>`},{rollMode:game.settings.get('core','rollMode')});}
}
class CarlSheet extends HandlebarsApplicationMixin(foundry.applications.sheets.ActorSheetV2){
 static DEFAULT_OPTIONS={tag:'form',classes:['carl'],position:{width:790,height:820},form:{submitOnChange:true},actions:{stat:async function(e,t){if(this.actor.type==='crawler')await this.actor.check(t.dataset.stat.toUpperCase(),t.dataset.stat);},edit:function(e,t){this.actor.items.get(t.dataset.id)?.sheet.render(true);},use:async function(e,t){if(!this.isEditable)return;const i=this.actor.items.get(t.dataset.id);if(!i)return;const s=i.system;if(i.type==='spell'){if(this.actor.system.mana.value<s.manaCost)return ui.notifications.warn('Insufficient Mana.');await this.actor.update({'system.mana.value':this.actor.system.mana.value-s.manaCost});}if(this.actor.type==='crawler'&&this.actor.system.floor<6&&s.rank>15)ui.notifications.warn('Rank 16+ benefits unlock on Floor 6. Apply the eligible rank and effects manually.');if(this.actor.type==='crawler'&&!s.passive&&['skill','spell','weapon'].includes(i.type))await this.actor.check(i.name,s.stat,s.rank,s.rank===0&&i.type!=='spell');else await ChatMessage.create({speaker:ChatMessage.getSpeaker({actor:this.actor}),content:`<div class="carl-card"><small>${esc(i.type.toUpperCase())}</small><h3>${esc(i.name)}</h3><p>${esc(s.description)}</p></div>`});},damage:async function(e,t){if(!this.isEditable)return;const i=this.actor.items.get(t.dataset.id);if(!i?.system.damage)return;try{await new Roll(i.system.damage+(i.system.damageMod?`+${this.actor.system.stats[i.system.stat].mod}`:''),this.actor.getRollData()).toMessage({speaker:ChatMessage.getSpeaker({actor:this.actor}),flavor:`<div class="carl-card"><h3>${esc(i.name)} — Damage</h3></div>`},{rollMode:game.settings.get('core','rollMode')});}catch{ui.notifications.warn('Check the damage formula.');}},create:async function(e,t){if(this.isEditable)await this.actor.createEmbeddedDocuments('Item',[{name:'New '+t.dataset.type,type:t.dataset.type}]);},evade:async function(){if(this.actor.type==='crawler')await this.actor.check('Evade','dex');}}};
 static PARTS={body:{template:'systems/dungeon-crawler-carl/templates/actor.hbs'}};
 static TABS={primary:{tabs:[{id:'overview',label:'Crawler HUD'},{id:'abilities',label:'Skills & Spells'},{id:'inventory',label:'Inventory'},{id:'achievements',label:'Achievements'},{id:'notes',label:'Notes'}],initial:'overview'}};
 async _prepareContext(options){const c=await super._prepareContext(options);return {...c,actor:this.actor,system:this.actor.system,mob:this.actor.type==='mob',stats:Object.entries(this.actor.system.stats).map(([key,s])=>({key,...s,label:key.toUpperCase()})),groups:['skill','spell','weapon','gear','race','class','achievement'].map(type=>({type,items:this.actor.items.filter(i=>i.type===type)})),slots:Array.from({length:this.actor.system.health.max},(_,i)=>({filled:i<this.actor.system.health.value})),modes:{normal:"Normal",advantage:"Advantage",disadvantage:"Disadvantage"},tabs:this._prepareTabs('primary')};}
}
class CarlItemSheet extends HandlebarsApplicationMixin(foundry.applications.sheets.ItemSheetV2){static DEFAULT_OPTIONS={tag:'form',classes:['carl'],position:{width:520,height:630},form:{submitOnChange:true}};static PARTS={body:{template:'systems/dungeon-crawler-carl/templates/item.hbs'}};async _prepareContext(o){return {...await super._prepareContext(o),item:this.item,system:this.item.system,stats:{str:"STR",int:"INT",con:"CON",dex:"DEX",cha:"CHA"}};}}
Hooks.once('init',()=>{CONFIG.Actor.documentClass=CarlActor;foundry.applications.apps.DocumentSheetConfig.registerSheet(Actor,'dungeon-crawler-carl',CarlSheet,{types:['crawler','mob'],makeDefault:true});foundry.applications.apps.DocumentSheetConfig.registerSheet(Item,'dungeon-crawler-carl',CarlItemSheet,{makeDefault:true});CONFIG.statusEffects=['Blinded','Blood Trail','Burned','Drowning','Dying','Enraged','Fatigued','Held','Major Injury','Minor Injury','Muted','Poisoned','Paralyzed','Queasy','Sepsis','Shit-Faced','Shocked','Sore as Shit','Staggered','Stiff Legs','Stunned','Take Down','Terrified','The Taint','Woozy'].map(label=>({id:label.toLowerCase().replaceAll(' ','-'),name:label,img:'icons/svg/aura.svg'}));});
Hooks.on('preCreateActor',(a)=>{a.updateSource({'prototypeToken.bar1.attribute':'health','prototypeToken.bar2.attribute':'mana','prototypeToken.actorLink':a.type==='crawler'});});
